### ISSUE TITLE
Addition of threshold modifier

### ISSUE THREAD

**Issue by MikeHarrison** [heidkaemper/alpinejs-intersect-class#2]
Hi,

Firstly thanks for this plugin, it is a lovely simple way for me to include some scroll-based animations in my builds.

One thing that would be useful is to include the threshold modifier (https://alpinejs.dev/plugins/intersect#threshold) that is used in the Alpine plugin. I understand this would add some complexity, but this bit of extra control of when animations trigger would be a great addition.

Please let me know if this might be possible

**Comment by heidkaemper** [comment]
Yea, good suggestion! I just released v1.0.7 with threshold modifiers:
https://github.com/heidkaemper/alpinejs-intersect-class/releases/tag/1.0.7

**Comment by MikeHarrison** [comment]
That's awesome, thank you! I will give it a spin this week and let you know how I get on.

**Comment by MikeHarrison** [comment]
Hi! I have added this to my project, and there is a small issue. 

If an element is within the viewport on page load, even if the amount of it visible is less than the specified threshold, the class is applied. For instance if I set `x-intersect-class.threshold.50="fade-in"`, any element in the viewport will be faded in even if what is visible is less than 50% of that element.

I have created a quick Codepen to illustrate this: https://codepen.io/MikeHarrisonDesign/pen/wvZRgva. If you run this in debug mode you should see this behaviour

**Comment by heidkaemper** [comment]
This is hopefully fixed with 1.0.8. Note that the CDN version might take a few hours until the new version is being delivered.
